<template>
  <MainHeader
    ref="mainHeader"
    :link-border-color="'#4d4d4d'"
    :image-src="'/images/supreme_logo.png'"
  />
  <div class="title-screen ml-lg-5 pl-lg-5">
    <div class="align-items-center d-flex">
      <div class="col-lg-11">
        <div class="title-first">
          <span style="color: #c52729;">Privacy</span> Policy
        </div>
      </div>
    </div>
  </div>
  <SectionLine />
  <div class="privacy-policy ml-lg-5 pl-lg-5">
    <div class="align-items-center d-flex">
      <div class="col-lg-11">
        <div class="row">
          <div class="name-part-policy col-lg-4">
            Interpretation <br> and Definitions
          </div>
          <div class="text-part-policy col-lg-8 col-12">
            <div>
              <span style="color: #c52729;">Interpretation</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Definitions</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              For the purposes of this Privacy Policy:
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) (address), Canada.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Country</span> refers to: British Columbia, Canada
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Device </span>means any device that can access the Service such as a computer, a cellphone or a digital tablet.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Personal</span> Data is any information that relates to an identified or identifiable individual.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Service</span> refers to the Website.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Service</span> Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Usage</span> Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Website</span> refers to Supreme Facade, accessible from https://www.supreme-facade.ca/
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="name-part-policy col-lg-4">
            Collecting and Using <br> Your Personal Data
          </div>
          <div class="text-part-policy col-lg-8 col-12">
            <div class="">
              <span style="color: #c52729;">Types of Data Collected</span>
            </div>
            <div class="line mt-2" />
            <div class="text-title">
              Personal Data
            </div>
            <div class="text mt-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              <ul class="mt-3">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
              </ul>
            </div>
            <div class="text-title">
              Usage Data
            </div>
            <div class="text mt-3">
              <div class="mt-4">
                Usage Data is collected automatically when using the Service.
              </div>
              <div class="mt-4">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </div>
              <div class="mt-4">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </div>
              <div class="mt-4">
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Tracking Technologies and Cookies</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
              </div>
              <div class="mt-4">
                Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.
              </div>
              <div class="mt-4">
                We use both Session and Persistent Cookies for the purposes set out below:
              </div>
              <div class="mt-4">
                Necessar y / Essential Cookies
              </div>
              <div class="mt-4">
                Type: Session Cookies
              </div>
              <div class="mt-4">
                Administered by: Us
              </div>
              <div class="mt-4">
                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
              </div>
              <div class="mt-4">
                Cookies Policy / Notice Acceptance Cookies
              </div>
              <div class="mt-4">
                Type: Persistent Cookies
              </div>
              <div class="mt-4">
                Administered by: Us
              </div>
              <div class="mt-4">
                Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
              </div>
              <div class="mt-4">
                Functionality Cookies
              </div>
              <div class="mt-4">
                Type: Persistent Cookies
              </div>
              <div class="mt-4">
                Administered by: Us
              </div>
              <div class="mt-4">
                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Use of Your Personal Data</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              The Company may use Personal Data for the following purposes:
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">To provide and maintain our Service,</span>  including to monitor the usage of our Service.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">To manage Your requests:</span> To attend and manage Your requests to Us.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
              </div>
              <div class="mt-4">
                <span style="color: #212529; font-weight: 600;">For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Retention of Your Personal Data</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              The Company may use Personal Data for the following purposes:
              <div class="mt-4">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </div>
              <div class="mt-4">
                The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Transfer of Your Personal Data</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              <div class="mt-4">
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
              </div>
              <div class="mt-4">
                Your consent to this Privacy Policy followed by Your using of submission of such information represents Your agreement to that transfer.
              </div>
              <div class="mt-4">
                The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Delete Your Personal Data</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              <div class="mt-4">
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
              </div>
              <div class="mt-4">
                Our Service may give You the ability to delete certain information about You from within the Service.
              </div>
              <div class="mt-4">
                You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
              </div>
              <div class="mt-4">
                Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Types of Data Collected</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              <div class="text-title">
                Business Transactions
              </div>
              <div class="mt-4">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </div>
              <div class="text-title">
                Law enforcement
              </div>
              <div class="mt-4">
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </div>
              <div class="text-title">
                Other legal requirements
              </div>
              <div class="mt-4">
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              </div>
              <ul class="mt-3">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Security of Your Personal Data</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              <div class="mt-4">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </div>
            </div>
            <div class="text-header mt-5">
              <span style="color: #c52729;">Compliance</span>
            </div>
            <div class="line mt-2" />
            <div class="text mt-3">
              <div class="mt-4">
                We are committed to ensuring the privacy and protection of your personal information in accordance with applicable privacy laws and regulations in Canada. This includes, but is not limited to, compliance with the federal Personal Information Protection and Electronic Documents Act (PIPEDA) and relevant provincial privacy legislation. We strive to implement appropriate safeguards and practices to safeguard your personal information and maintain compliance with these laws.
              </div>
              <div class="mt-4">
                By accessing or using our website, you acknowledge and consent to the collection, use, and disclosure of your personal information as outlined in this Privacy Policy, and you agree to our compliance with applicable privacy laws.
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="name-part-policy col-lg-4">
            Links to Other Websites
          </div>
          <div class="text-part-policy col-lg-8 col-12">
            <div class="text mt-3">
              <div class="">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
              </div>
              <div class="mt-4">
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="name-part-policy col-lg-4">
            Contact Us
          </div>
          <div class="text-part-policy col-lg-8 col-12">
            <div class="text mt-3">
              <div class="">
                If you have any questions about this Privacy Policy, You can contact us:
              </div>
              <ul class="mt-3">
                <li>By email: <span style="color: #212529;">info@supreme-facade.ca</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <MainFooter class="main-footer" />
</template>

<script>
import SectionLine from '@/components/SectionLine.vue'
import MainFooter from '@/components/MainFooter.vue'
import MainHeader from '@/components/MainHeader.vue'

export default {
  components: {
    MainFooter,
    SectionLine,
    MainHeader
  },
  mounted () {
    window.addEventListener('scroll', this.handleScroll)
  },
  methods: {
    handleScroll () {
      const mainHeader = this.$refs.mainHeader
      if (mainHeader) {
        if (window.scrollY > 0) {
          mainHeader.$el.classList.add('fixed-header')
        } else {
          mainHeader.$el.classList.remove('fixed-header')
        }
      }
    }
  }
}
</script>

<style scoped>
.text-title {
  color: #212529;
  font-weight: 550;
  margin-top: 1.8rem !important;
}

.text {
  font-size: 1.9rem;
  color: #707070;
  line-height: 1.2;
}

.text-header {
  font-weight: 500;
  margin-top: 6rem !important;
}

@media (max-width: 768px) {
  .text-header {
    font-size: 2rem;
  }
  .text {
    font-size: 1.5rem;
  }
}

.line {
  width: 100%;
  border-top: 1px solid #e2e2e2;
}

.privacy-policy {
  margin-top: 5vh;
}

.name-part-policy {
  font-size: 2.8rem;
  line-height: 1.2;
}

.text-part-policy {
  font-size: 2.2rem;
}

@media (max-width: 768px) {
  .name-part-policy {
    font-size: 2rem;
  }
  .text-part-policy {
    margin-top: 3vh;
  }
}

.main-footer {
    margin-top: 30vh;
}

.title-screen {
  font-size: 5rem;
  align-items: center;
  margin-top: 10vh;
}

@media (max-width: 768px) {
  .title-screen {
    font-size: 2.5rem !important;
    margin-top: 5vh;
  }
}
</style>
